#!/usr/bin/env python3
"""Keep every wiki page on the same head block, header and footer.

The site has no build step, so the shared chrome is copied into each page
between markers. This script rewrites those blocks from ``wiki/partials/``;
``--check`` (run in CI) fails instead of writing when any page differs, and
also checks the language wiring the chrome depends on:

* ``<body data-section>`` matches the page's section, which is what highlights
  the current item in the header (CSS only, no JS needed);
* a language-neutral page carries ``<html data-lang-neutral>``; an article
  carries ``<html data-page-lang>`` and ``<link rel="alternate">`` to both
  language versions, each of which exists and links back;
* the docs page carries neither (its script decides from the URL);
* every cache-busting ``?v=`` token (pages, site scripts, the generator) is
  the one in ``partials/site-head.html``: ``_headers`` lets browsers keep
  JS and CSS for an hour, so a module bumped alone can meet a cached copy of
  the module it imports and leave the page blank. Bump with one replace
  across ``wiki/``.

The Alpha Library pages under ``alpha-library/content/`` are generated by
``build_alpha_library.py``, which inserts the same partials itself.

Usage:
    python wiki/scripts/sync_site_chrome.py          # rewrite blocks
    python wiki/scripts/sync_site_chrome.py --check  # CI
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

WIKI = Path(__file__).resolve().parents[1]
PARTIALS = WIKI / "partials"
BLOCKS = ("site-head", "site-header", "site-footer")
SECTIONS = {
    "home": "home",
    "docs": "docs",
    "tutorials": "tutorials",
    "alpha-library": "alpha",
    "research-lab": "lab",
}
# Pages whose URL fixes their language: every page in these folders except
# the folder's index.
ARTICLE_DIRS = ("tutorials", "research-lab/posts")
HTML_LANG = {"en": "en", "zh": "zh-CN"}


def pages() -> list[Path]:
    """Return every hand-written page that carries the shared chrome.

    Returns:
        Page paths, sorted.
    """
    found = []
    for path in sorted(WIKI.rglob("*.html")):
        rel = path.relative_to(WIKI).as_posix()
        if rel == "index.html" or rel.startswith(("partials/", "alpha-library/content/")):
            continue
        found.append(path)
    return found


def partial(name: str) -> str:
    """Return a partial's text without its trailing newline.

    Args:
        name: Block name, e.g. ``site-header``.

    Returns:
        The partial markup.
    """
    return (PARTIALS / f"{name}.html").read_text(encoding="utf-8").rstrip("\n")


def block_re(name: str) -> re.Pattern[str]:
    """Match one marked block, capturing its indentation.

    Args:
        name: Block name.

    Returns:
        A compiled pattern.
    """
    return re.compile(
        rf"^(?P<indent>[ \t]*)<!-- {name}:start -->\n.*?^[ \t]*<!-- {name}:end -->$",
        re.S | re.M,
    )


def render_block(name: str, indent: str) -> str:
    """Render a block with its markers at the given indentation.

    Args:
        name: Block name.
        indent: Leading whitespace of the start marker.

    Returns:
        The block text.
    """
    body = "\n".join(f"{indent}{line}" if line else "" for line in partial(name).splitlines())
    return f"{indent}<!-- {name}:start -->\n{body}\n{indent}<!-- {name}:end -->"


def is_article(rel: str) -> bool:
    """Whether a page's URL fixes its language.

    Args:
        rel: Path relative to the wiki root.

    Returns:
        True for tutorial and research articles.
    """
    folder, _, name = rel.rpartition("/")
    return folder in ARTICLE_DIRS and name != "index.html"


def wiring_problems(path: Path, text: str) -> list[str]:
    """Check the section and language attributes of one page.

    Args:
        path: The page.
        text: Its contents.

    Returns:
        Human-readable problems, empty when the page is wired correctly.
    """
    rel = path.relative_to(WIKI).as_posix()
    problems = []
    section = SECTIONS.get(rel.split("/", 1)[0])
    body = re.search(r"<body\b[^>]*>", text)
    if not body or f'data-section="{section}"' not in body.group(0):
        problems.append(f'{rel}: <body> needs data-section="{section}"')
    html = re.search(r"<html\b[^>]*>", text)
    html_tag = html.group(0) if html else ""
    if rel.startswith("docs/"):
        if "data-lang-neutral" in html_tag or "data-page-lang" in html_tag:
            problems.append(f"{rel}: the docs decide their language from the URL; no language attribute on <html>")
        return problems
    if not is_article(rel):
        if "data-lang-neutral" not in html_tag:
            problems.append(f"{rel}: <html> needs data-lang-neutral")
        return problems
    declared = re.search(r'data-page-lang="(en|zh)"', html_tag)
    if not declared:
        problems.append(f'{rel}: <html> needs data-page-lang="en" or "zh"')
        return problems
    if f'lang="{HTML_LANG[declared.group(1)]}"' not in html_tag:
        problems.append(f"{rel}: <html lang> disagrees with data-page-lang")
    for lang, code in HTML_LANG.items():
        link = re.search(rf'<link rel="alternate" hreflang="{code}" href="([^"]+)">', text)
        if not link:
            problems.append(f"{rel}: missing <link rel=\"alternate\" hreflang=\"{code}\">")
            continue
        target = WIKI / link.group(1).lstrip("/")
        if not target.is_file():
            problems.append(f"{rel}: alternate {code} points at missing {link.group(1)}")
        elif lang == declared.group(1) and target != path:
            problems.append(f"{rel}: its own-language alternate points elsewhere ({link.group(1)})")
    return problems


VERSION_RE = re.compile(r'\?v=([\w-]+)|VERSION = "([\w-]+)"')


def version_problems() -> list[str]:
    """Check that every cache-busting token matches the head block's.

    Returns:
        Human-readable problems, empty when all tokens agree.
    """
    head = re.search(r"styles\.css\?v=([\w-]+)", partial("site-head"))
    if not head:
        return ["partials/site-head.html: no ?v= token on styles.css"]
    expected = head.group(1)
    files = pages() + [
        path for path in sorted(WIKI.rglob("*.js"))
        if not path.relative_to(WIKI).as_posix().startswith(("alpha-library/content/", "functions/"))
    ] + [WIKI / "scripts" / "build_alpha_library.py"]
    problems = []
    for path in files:
        for match in VERSION_RE.finditer(path.read_text(encoding="utf-8")):
            found = match.group(1) or match.group(2)
            if found != expected:
                rel = path.relative_to(WIKI).as_posix()
                problems.append(f"{rel}: version {found}, the head block uses {expected} (bump them together)")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Rewrite or check the shared chrome of every page.

    Args:
        argv: Command-line arguments.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail on any difference instead of writing")
    args = parser.parse_args(argv)

    problems: list[str] = []
    changed: list[str] = []
    for path in pages():
        rel = path.relative_to(WIKI).as_posix()
        text = path.read_text(encoding="utf-8")
        updated = text
        for name in BLOCKS:
            matches = list(block_re(name).finditer(updated))
            if len(matches) != 1:
                problems.append(f"{rel}: expected one <!-- {name}:start/end --> block, found {len(matches)}")
                continue
            match = matches[0]
            updated = updated[: match.start()] + render_block(name, match.group("indent")) + updated[match.end():]
        problems.extend(wiring_problems(path, updated))
        if updated != text:
            changed.append(rel)
            if not args.check:
                path.write_text(updated, encoding="utf-8")

    problems.extend(version_problems())
    if args.check and changed:
        problems.extend(f"{rel}: shared chrome differs from wiki/partials/ (run sync_site_chrome.py)" for rel in changed)
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    verb = "checked" if args.check else f"synced ({len(changed)} rewritten)"
    print(f"site chrome {verb}: {len(pages())} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
